# Generated by Django 5.2.4 on 2025-07-06 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_make_image_nullable"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="total",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="price",
        ),
        migrations.AddField(
            model_name="order",
            name="completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="external_image_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name="CartItem",
        ),
    ]
